### ISSUE TITLE
build instructions

### ISSUE THREAD

**Issue by Khady** [gongzhitaao/orgcss#5]
Hi,

I'm sorry if it is obvious for someone who knows the css world, but I struggle to build this project by hand. Would you mind providing build instructions?

I guess it requires running gulp. But only after an export of index.org and ref.bib?

```
$ ./node_modules/.bin/gulp 
[08:09:47] Using gulpfile ~/Code/github/orgcss/gulpfile.js
[08:09:47] Starting 'default'...
[08:09:47] Starting 'build'...
[08:09:47] Starting 'clean'...
[08:09:47] Finished 'clean' after 2.78 ms
[08:09:47] Starting 'pages'...
[08:09:47] Starting 'styles'...
[08:09:47] Starting 'misc'...
[08:09:48] 'pages' errored after 554 ms
[08:09:48] Error: File not found with singular glob: /home/louis/Code/github/orgcss/src/index.html (if this was purposeful, use `allowEmpty` option)
    at Glob.<anonymous> (/home/louis/Code/github/orgcss/node_modules/glob-stream/readable.js:84:17)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at Glob.emit (events.js:211:7)
    at Glob._finish (/home/louis/Code/github/orgcss/node_modules/glob/glob.js:197:8)
    at done (/home/louis/Code/github/orgcss/node_modules/glob/glob.js:182:14)
    at Glob._processSimple2 (/home/louis/Code/github/orgcss/node_modules/glob/glob.js:688:12)
    at /home/louis/Code/github/orgcss/node_modules/glob/glob.js:676:10
    at Glob._stat2 (/home/louis/Code/github/orgcss/node_modules/glob/glob.js:772:12)
    at lstatcb_ (/home/louis/Code/github/orgcss/node_modules/glob/glob.js:764:12)
[08:09:48] 'build' errored after 558 ms
[08:09:48] 'default' errored after 559 ms
[08:09:48] The following tasks did not complete: styles, misc
[08:09:48] Did you forget to signal async completion?
```

**Comment by gongzhitaao** [comment]
It is not the gulp fault.  In the `src/` folder, there is only `index.org` (Emacs [org](https://orgmode.org/) files), no `index.html`.  I use Emacs to export `index.org` to `index.html`.
The gulp watches the change of `index.html` and rebuild the whole repo once I change `index.org`.  I did not include the `index.html` file since it is temporary file for me.
